// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: rom_map.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.0.1 Build 232 06/12/2013 SP 1 SJ Full Version
// ************************************************************


//Copyright (C) 1991-2013 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altsyncram CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone II" ENABLE_RUNTIME_MOD="NO" INIT_FILE="rom_map.mif" NUMWORDS_A=32768 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="CLOCK0" WIDTH_A=3 WIDTH_BYTEENA_A=1 WIDTHAD_A=15 address_a clock0 q_a
//VERSION_BEGIN 13.0 cbx_altsyncram 2013:06:12:18:03:40:SJ cbx_cycloneii 2013:06:12:18:03:40:SJ cbx_lpm_add_sub 2013:06:12:18:03:40:SJ cbx_lpm_compare 2013:06:12:18:03:40:SJ cbx_lpm_decode 2013:06:12:18:03:40:SJ cbx_lpm_mux 2013:06:12:18:03:40:SJ cbx_mgl 2013:06:12:18:04:42:SJ cbx_stratix 2013:06:12:18:03:40:SJ cbx_stratixii 2013:06:12:18:03:40:SJ cbx_stratixiii 2013:06:12:18:03:40:SJ cbx_stratixv 2013:06:12:18:03:40:SJ cbx_util_mgl 2013:06:12:18:03:40:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//lpm_decode DEVICE_FAMILY="Cyclone II" LPM_DECODES=8 LPM_WIDTH=3 data enable eq
//VERSION_BEGIN 13.0 cbx_cycloneii 2013:06:12:18:03:40:SJ cbx_lpm_add_sub 2013:06:12:18:03:40:SJ cbx_lpm_compare 2013:06:12:18:03:40:SJ cbx_lpm_decode 2013:06:12:18:03:40:SJ cbx_mgl 2013:06:12:18:04:42:SJ cbx_stratix 2013:06:12:18:03:40:SJ cbx_stratixii 2013:06:12:18:03:40:SJ  VERSION_END

//synthesis_resources = lut 8 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  rom_map_decode
	( 
	data,
	enable,
	eq) /* synthesis synthesis_clearbox=1 */;
	input   [2:0]  data;
	input   enable;
	output   [7:0]  eq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [2:0]  data;
	tri1   enable;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [2:0]  data_wire;
	wire  enable_wire;
	wire  [7:0]  eq_node;
	wire  [7:0]  eq_wire;
	wire  [3:0]  w_anode109w;
	wire  [3:0]  w_anode126w;
	wire  [3:0]  w_anode136w;
	wire  [3:0]  w_anode146w;
	wire  [3:0]  w_anode156w;
	wire  [3:0]  w_anode166w;
	wire  [3:0]  w_anode176w;
	wire  [3:0]  w_anode186w;

	assign
		data_wire = data,
		enable_wire = enable,
		eq = eq_node,
		eq_node = eq_wire[7:0],
		eq_wire = {w_anode186w[3], w_anode176w[3], w_anode166w[3], w_anode156w[3], w_anode146w[3], w_anode136w[3], w_anode126w[3], w_anode109w[3]},
		w_anode109w = {(w_anode109w[2] & (~ data_wire[2])), (w_anode109w[1] & (~ data_wire[1])), (w_anode109w[0] & (~ data_wire[0])), enable_wire},
		w_anode126w = {(w_anode126w[2] & (~ data_wire[2])), (w_anode126w[1] & (~ data_wire[1])), (w_anode126w[0] & data_wire[0]), enable_wire},
		w_anode136w = {(w_anode136w[2] & (~ data_wire[2])), (w_anode136w[1] & data_wire[1]), (w_anode136w[0] & (~ data_wire[0])), enable_wire},
		w_anode146w = {(w_anode146w[2] & (~ data_wire[2])), (w_anode146w[1] & data_wire[1]), (w_anode146w[0] & data_wire[0]), enable_wire},
		w_anode156w = {(w_anode156w[2] & data_wire[2]), (w_anode156w[1] & (~ data_wire[1])), (w_anode156w[0] & (~ data_wire[0])), enable_wire},
		w_anode166w = {(w_anode166w[2] & data_wire[2]), (w_anode166w[1] & (~ data_wire[1])), (w_anode166w[0] & data_wire[0]), enable_wire},
		w_anode176w = {(w_anode176w[2] & data_wire[2]), (w_anode176w[1] & data_wire[1]), (w_anode176w[0] & (~ data_wire[0])), enable_wire},
		w_anode186w = {(w_anode186w[2] & data_wire[2]), (w_anode186w[1] & data_wire[1]), (w_anode186w[0] & data_wire[0]), enable_wire};
endmodule //rom_map_decode


//lpm_mux DEVICE_FAMILY="Cyclone II" LPM_SIZE=8 LPM_WIDTH=3 LPM_WIDTHS=3 data result sel
//VERSION_BEGIN 13.0 cbx_lpm_mux 2013:06:12:18:03:40:SJ cbx_mgl 2013:06:12:18:04:42:SJ  VERSION_END

//synthesis_resources = lut 15 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  rom_map_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [23:0]  data;
	output   [2:0]  result;
	input   [2:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [23:0]  data;
	tri0   [2:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [2:0]  result_node;
	wire  [2:0]  sel_ffs_wire;
	wire  [2:0]  sel_node;
	wire  [7:0]  w_data205w;
	wire  [3:0]  w_data227w;
	wire  [3:0]  w_data228w;
	wire  [7:0]  w_data276w;
	wire  [3:0]  w_data298w;
	wire  [3:0]  w_data299w;
	wire  [7:0]  w_data345w;
	wire  [3:0]  w_data367w;
	wire  [3:0]  w_data368w;
	wire  [1:0]  w_sel229w;
	wire  [1:0]  w_sel300w;
	wire  [1:0]  w_sel369w;

	assign
		result = result_node,
		result_node = {((sel_node[2] & (((w_data368w[1] & w_sel369w[0]) & (~ (((w_data368w[0] & (~ w_sel369w[1])) & (~ w_sel369w[0])) | (w_sel369w[1] & (w_sel369w[0] | w_data368w[2]))))) | ((((w_data368w[0] & (~ w_sel369w[1])) & (~ w_sel369w[0])) | (w_sel369w[1] & (w_sel369w[0] | w_data368w[2]))) & (w_data368w[3] | (~ w_sel369w[0]))))) | ((~ sel_node[2]) & (((w_data367w[1] & w_sel369w[0]) & (~ (((w_data367w[0] & (~ w_sel369w[1])) & (~ w_sel369w[0])) | (w_sel369w[1] & (w_sel369w[0] | w_data367w[2]))))) | ((((w_data367w[0] & (~ w_sel369w[1])) & (~ w_sel369w[0])) | (w_sel369w[1] & (w_sel369w[0] | w_data367w[2]))) & (w_data367w[3] | (~ w_sel369w[0])))))), ((sel_node[2] & (((w_data299w[1] & w_sel300w[0]) & (~ (((w_data299w[0] & (~ w_sel300w[1])) & (~ w_sel300w[0])) | (w_sel300w[1] & (w_sel300w[0] | w_data299w[2]))))) | ((((w_data299w[0] & (~ w_sel300w[1])) & (~ w_sel300w[0])) | (w_sel300w[1] & (w_sel300w[0] | w_data299w[2]))) & (w_data299w[3] | (~ w_sel300w[0]))))) | ((~ sel_node[2]) & (((w_data298w[1] & w_sel300w[0]) & (~ (((w_data298w[0] & (~ w_sel300w[1])) & (~ w_sel300w[0])) | (w_sel300w[1] & (w_sel300w[0] | w_data298w[2]))))) | ((((w_data298w[0] & (~ w_sel300w[1])) & (~ w_sel300w[0])) | (w_sel300w[1] & (w_sel300w[0] | w_data298w[2]))) & (w_data298w[3] | (~ w_sel300w[0])))))), ((sel_node[2] & (((w_data228w[1] & w_sel229w[0]) & (~ (((w_data228w[0] & (~ w_sel229w[1])) & (~ w_sel229w[0])) | (w_sel229w[1] & (w_sel229w[0] | w_data228w[2]))))) | ((((w_data228w[0] & (~ w_sel229w[1])) & (~ w_sel229w[0])) | (w_sel229w[1] & (w_sel229w[0] | w_data228w[2]))) & (w_data228w[3] | (~ w_sel229w[0]))))) | ((~ sel_node[2]) & (((w_data227w[1] & w_sel229w[0]) & (~ (((w_data227w[0] & (~ w_sel229w[1])) & (~ w_sel229w[0])) | (w_sel229w[1] & (w_sel229w[0] | w_data227w[2]))))) | ((((w_data227w[0] & (~ w_sel229w[1])) & (~ w_sel229w[0])) | (w_sel229w[1] & (w_sel229w[0] | w_data227w[2]))) & (w_data227w[3] | (~ w_sel229w[0]))))))},
		sel_ffs_wire = {sel[2:0]},
		sel_node = {sel_ffs_wire[2], sel[1:0]},
		w_data205w = {data[21], data[18], data[15], data[12], data[9], data[6], data[3], data[0]},
		w_data227w = w_data205w[3:0],
		w_data228w = w_data205w[7:4],
		w_data276w = {data[22], data[19], data[16], data[13], data[10], data[7], data[4], data[1]},
		w_data298w = w_data276w[3:0],
		w_data299w = w_data276w[7:4],
		w_data345w = {data[23], data[20], data[17], data[14], data[11], data[8], data[5], data[2]},
		w_data367w = w_data345w[3:0],
		w_data368w = w_data345w[7:4],
		w_sel229w = sel_node[1:0],
		w_sel300w = sel_node[1:0],
		w_sel369w = sel_node[1:0];
endmodule //rom_map_mux

//synthesis_resources = lut 23 M4K 24 reg 6 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  rom_map_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [14:0]  address_a;
	input   clock0;
	output   [2:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[2:0]	address_reg_a;
	reg	[2:0]	out_address_reg_a;
	wire  [7:0]   wire_deep_decode_eq;
	wire  [2:0]   wire_mux2_result;
	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [2:0]  address_a_sel;
	wire  [14:0]  address_a_wire;

	// synopsys translate_off
	initial
		address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  address_reg_a <= address_a_sel;
	// synopsys translate_off
	initial
		out_address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  out_address_reg_a <= address_reg_a;
	rom_map_decode   deep_decode
	( 
	.data(address_a_wire[14:12]),
	.enable(1'b1),
	.eq(wire_deep_decode_eq));
	rom_map_mux   mux2
	( 
	.data({wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]}),
	.result(wire_mux2_result),
	.sel(out_address_reg_a));
	cycloneii_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[0]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "rom_map.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 2048'h00100004000000810400100000000080000000080000000040000000040000000060000000020000000020000000000000000000000400010000000000000200000000000008000000000000100800010100808000000006000000004000000000000000002000000001000040000000008001000020000000000000000020000000020000800010000C00010000600008000000000020000800000200004000000000000000000000000001000000001000080001000040004000000000000020001000000000000000000000030000000020000000018000200008000000008000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_0.mem_init1 = 2048'h0800010000400000000400010000200018000200008000000008000300000000000000000100004000000400000100000000080300028100200000000001000000000000000000000000000000000000400010000400008000200000000200000000000008000000000000100000000000000000080010400000000000000000000000000000000000000000000000020000400020000000010000400000000000018000000000000000018000200000000000000000100000000080000000080A10010080303030100200000040001000000000000000001000000000800000000C000000000000100006000000004000000004000000002000000000000000,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_width = 12,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "clock0",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 4095,
		ram_block1a_0.port_a_logical_ram_depth = 32768,
		ram_block1a_0.port_a_logical_ram_width = 3,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[0]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "rom_map.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 2048'h0000000400010081040010000200000000000000000000004000100000000000000000000002000000002000000001000000001000000001000000001800020000800000000000000000802000080400010000C0000000020000000020000000060000400020000400020000400018001080020000000008000200008000000008000200008000100000000100000000000002008040200000040201000000000000020000800000001000010000000000000C00000000402002000C0000000000000000020000000000000000020000400010000000010000000008000000008000000004000000004000000000000000000000000000000000000000000000,
		ram_block1a_1.mem_init1 = 2048'h080002000080001000040000000000001800000000000020000000000000C0001000040000000040000800020001000100100002010001002000000000000000200010000000000000000008000000000000100000000000004000000002000000000000000000000000000000000001000020001000104000800000000800010000400000000400000000000000000000000000200000000000000000000000000180002000000000000000000000000000000080000000080000008040000808100100803000301802000000400020000400000000000010000000008000000004000000000000000004000100004000000006000000000000000001000000,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_width = 12,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "clock0",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 4095,
		ram_block1a_1.port_a_logical_ram_depth = 32768,
		ram_block1a_1.port_a_logical_ram_width = 3,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[0]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "rom_map.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 2048'h00000000000000000000000000000000002000000000000000000000000000000000000800000000000010000800000000400000000000000000000000000000000000000000000100000000000000000000000000100000000080000000080000000000001000000000800000000008000000000000000000000000000000000000000000400000000000000000000000000000000000100000000000000000100000000100002000000000000080000000020000000020000000000001000000000000000000800020000800000000000000000400000000000000000000000000000000000000000000000002000000000000000000000000000000000000,
		ram_block1a_2.mem_init1 = 2048'h0000000000000000000000000000000000000000000000000000000000000000000000000000000008000000018040A010000000020000400010000400000000000000000000008000100000000000008000000000000000000000080000000000003000000002000000000000020000000000000008000000000020000000000000000000000000010000200000000000000000000000000200000000100002000000000000180000000000000000080000000000000000040100000000281000020000000000000000010000000000000000010000000008000100000000000000000100004000000000000000002000000000000080000000000002000040,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_width = 12,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "clock0",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 4095,
		ram_block1a_2.port_a_logical_ram_depth = 32768,
		ram_block1a_2.port_a_logical_ram_width = 3,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[1]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "rom_map.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 2048'h030100000000000002000040001000000001000020000800000001800010000000010000400010000000000000400008000200000000000000000200000000200820000100004000100002000000000000080000000040000000040000000020000000000000800010000000000000400030000000010000200000000000010000000000000000000000000000000000004000000002010080000000080000008040001000020000000060000000020000800020000C000000000000100000000000002010000000000000000000080002000000001000040001000000000000020000800020000C02010000A000000004000000000000000000000000000000,
		ram_block1a_3.mem_init1 = 2048'h00200008000200000000200008000000000000100002000000002000100000400080002000080000000040000000040000000020000000020000000020000000030000400000000000010000200010000000000000000008000000000000000004010000004028000010010080200000100001000000001000040001000000000000000000800000000000010000000000000400010000200000000600008000200000000300004000100000000000000400000000000080000000000000000040000000040000000040000000000000000020000000000000000010000400000000000008000000008000000008000000000000080804000081402000080200,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_width = 12,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "clock0",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_3.port_a_first_address = 4096,
		ram_block1a_3.port_a_first_bit_number = 0,
		ram_block1a_3.port_a_last_address = 8191,
		ram_block1a_3.port_a_logical_ram_depth = 32768,
		ram_block1a_3.port_a_logical_ram_width = 3,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[1]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "rom_map.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 2048'h030080200000000000000040000000000000000000000800000000000000000800010000400010000400000000400000000200000000000000000200004000300800000000004000100000000000000000080001000000000000000000000000000000000000800000000400010000000010000000010000200008000000000000100000000000008000000000000080004000180802010000002000080202008000001000020000000040000000000000800000000800010000C0000000000001000060000000020000800000000800020000400010000400000000200010000200004000200000020100004000100006000000000000080002000080000000,
		ram_block1a_4.mem_init1 = 2048'h00000000000200000000000008000200000000000002000100002000180010400080002000000000000040000000040000000000000000000000000020000000010000000010000000008000000000000000018000000000000000008000100008010000800000040A00010000200010100001000000003000000000000000001800000000000000000000000000000010000400000000000000000000000000200000000000000000100004000100810400000000000000002000080000000040000000040000000020000400020000000020000000000000000000000400010000000000000000008000000000000100008010080804010001020000000403,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_width = 12,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "clock0",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_4.port_a_first_address = 4096,
		ram_block1a_4.port_a_first_bit_number = 1,
		ram_block1a_4.port_a_last_address = 8191,
		ram_block1a_4.port_a_logical_ram_depth = 32768,
		ram_block1a_4.port_a_logical_ram_width = 3,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[1]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "rom_map.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 2048'h00000000200008000100000000000000000080000000000000000000000000000000000080000000020000000020000000000000000020000400010000000000000040000000000000000000008000000000000000000000000000000080000000000002000000000000000002000000000000000000800000000000000000800000000800020000400010000400010000201000000000000000000000000100000000000004000100000000180000000000000000000000000000000000040000000000000800000000000020000000010000000000000000000000000008000000000000000000000000000000000000000100006000000000000000002000,
		ram_block1a_5.mem_init1 = 2048'h00400000000000000000100000000000000000000000000000000000000800000000000000000001000000000000000001000000000000000000400000000000000000000000000200000000000008000000000000200000000000000000000000000080000000100002000000103020080200000040000000000000000000000000010000000000000C00000000400000000200000000400000000000000000000000000000000000000000000000000000100002000000000000000000000000001000000000000000000000000000000010000800010000400000000000000000000010000200000000000000000000000000000000020200000020000000,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_width = 12,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "clock0",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_5.port_a_first_address = 4096,
		ram_block1a_5.port_a_first_bit_number = 2,
		ram_block1a_5.port_a_last_address = 8191,
		ram_block1a_5.port_a_logical_ram_depth = 32768,
		ram_block1a_5.port_a_logical_ram_width = 3,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "rom_map.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 2048'h00000400010000000000000000000000200000000200000000000000000000000000080002000000002000080000000000000000040000000000000800000080404020041002000100401000180000010000000008000200008000000000000100000000000000000080000000000002000000003000000001000040001000000000000000001000000000000100000800020000000000000000000000000000000200000000000000000000000000000004000080000000180000000000000000040000000040000000000000800040000404000101008000000800000000002010000000010000000000000000000000100008000000008000000004000000,
		ram_block1a_6.mem_init1 = 2048'h000000008000000000000100000000000002000000000000080401000080003000000001008020001000020000000000000400000000C000100000000100006000080002000000002010080001000040000000000000000000000000000000800000000800020000200000000202010000600008000200008000200008000200000000100000000000002000100002000080000000000001000000000000000001000040000000000000000000000002020140A050100004010080808000000002000180002000000000000000000800000000000040000000000000000030000800030000000010000400000000000010000000008000000008000800000000,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_width = 12,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "clock0",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_6.port_a_first_address = 8192,
		ram_block1a_6.port_a_first_bit_number = 0,
		ram_block1a_6.port_a_last_address = 12287,
		ram_block1a_6.port_a_logical_ram_depth = 32768,
		ram_block1a_6.port_a_logical_ram_width = 3,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "rom_map.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 2048'h00000000010000000000000000000000000000000000000000000000000180000000080002000000002000000000000040000000040000000000000800000080000020000008100100400018100C0000000000001800000000000000000800010000000000000A00000000200008000200008000000000000100004000100000000100002000000000000100000000080002000000000000000000000020000800000000000020000000000000000000000400000000200000000000000000000000000000000000000004000000004000040402018040A110000002020001002000000000010000200000000000008000000000000000000000100000000000,
		ram_block1a_7.mem_init1 = 2048'h0000000080000000000001000020000000020000800000000804030080C000300000020100000000080000000080000000040000000000000000020000000020000800020000800000100800000000000000000000018000000008000000000000000000000300000000000004020000002000000000000000002000080000000000001000040000000020001800000000800000000800000000C0001000040000000060001800020000000020000402020040004000000000818080A0000000020000000020000800000000C0000800040000000000000000020000800010000000030000000010000000000000000010000200000000000008040020008000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_width = 12,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "clock0",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_7.port_a_first_address = 8192,
		ram_block1a_7.port_a_first_bit_number = 1,
		ram_block1a_7.port_a_last_address = 12287,
		ram_block1a_7.port_a_logical_ram_depth = 32768,
		ram_block1a_7.port_a_logical_ram_width = 3,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[2]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "rom_map.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 2048'h10000000000000200000000200008000000000000100002000100000000000002000000000000080000000000000000080001000000000000040000000060000000000100400010000002000000001000000200000000000000000000004000000004000000000000000000000000000000000000000000002000000000000000000000000000800020000804002000000000000800010000400000000000000000000000000000004000100000000100000000000000000000002000180000000080001000000000000080000000000080000000000000000100001010280400000000400000000000010000000000000000000000000004000000000000080,
		ram_block1a_8.mem_init1 = 2048'h00000000000010000C00000000400008000000000000301000000000000000000004000000000000000000000000002000080001000000000000040000000000000000000000000000000000020000000010000400000000200000000200000000200000000000004000100000000000000000000000000000001000000001000040000000000001000040000000000000000020000000020000000000000000000000000000000000008000000800000000000000800800000001000010080000000000000000000000000000000000000000000020000800000000000000000000000000000020000000010000000008000000000000200000000000000000,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_width = 12,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "clock0",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_8.port_a_first_address = 8192,
		ram_block1a_8.port_a_first_bit_number = 2,
		ram_block1a_8.port_a_last_address = 12287,
		ram_block1a_8.port_a_logical_ram_depth = 32768,
		ram_block1a_8.port_a_logical_ram_width = 3,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[3]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "rom_map.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 2048'h00000000000C00010000400000000200008000000008000000000000100000000200000000000000000100002000180002000080410000000002000000000000040000000000000800000000000020000400000000000000000000008000200018000000008000000008000000000000000000000080000008000002008000A01010080200008000000000040001000000001000000000800010000000000000400000000400000000600008000200000000500000000200000000000002000000002000080810400080000000000001000000000000040000000000000000020000400020000000010000000010000000018000200000000000018000000000,
		ram_block1a_9.mem_init1 = 2048'h000000000000000000000008000000000020000004000000004000080000000000002000080001000000001000020001000000000800000000400000000C00000000C00000000800010000200000000600000000600000020201400000000800010100008000080000000100002000080000000040000800040000000020000000000000000030000800000000000010000000010000000010000200008000000008040800004000000000000100002000000000000000002000000003000020001000000001000020000000000000800000000000000000C0000000000000000000000800020080004020180008000000003018180C00010000200008000000,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_width = 12,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "clock0",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_9.port_a_first_address = 12288,
		ram_block1a_9.port_a_first_bit_number = 0,
		ram_block1a_9.port_a_last_address = 16383,
		ram_block1a_9.port_a_logical_ram_depth = 32768,
		ram_block1a_9.port_a_logical_ram_width = 3,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[3]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "rom_map.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 2048'h00000000000000000000000000000200000000200008000200008000000000000000004000000000000000002000100002000000400200080002000000001000000000000000000000000000000020000400010000000010000000008000200000000000008000000000000100004000000004000080000008080000008040201000000002020000000000000000000020000000000000800000000000000000400000000000000000600000000000000000000000000000000000000002000000000000080010000080002000080001000000000000040001000000000000020000000020000000000000000000000000010000200018000000008000000008,
		ram_block1a_10.mem_init1 = 2048'h20000000000000800010000800010000C00000000000000000000000000200000000000008000100000000000000000000000000000002000040000000040000000000000000020001000000000000020000400020000402000140001090000400818080000000000000010000000000000000004000000000000000004000000002000000001000000003000000001000000000000000001800020000000020000004082000400010000400010000000000000000008000000000000000002000100000000180002000000000000080002000000000000040001000000000000040000000000080400020081008000100401000000800000000200000000200,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_width = 12,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "clock0",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_10.port_a_first_address = 12288,
		ram_block1a_10.port_a_first_bit_number = 1,
		ram_block1a_10.port_a_last_address = 16383,
		ram_block1a_10.port_a_logical_ram_depth = 32768,
		ram_block1a_10.port_a_logical_ram_width = 3,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[3]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "rom_map.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 2048'h00800000000000000000000000000800000000000000000000000000200000000100000000100000000000000000000000000100000000000000000040000000000000000020000000020000000000000000000000000000000400000000000000000200010000000004000000000000000008000000004000000400010100010000000101000140201000000000000000000000000000400000000800000000800010000000008000000000000000000000000008000000000000100000000100000000100000000000000000000000000040000000000000000020000000000000000000000000020000400000000200000000000000000000000000200000,
		ram_block1a_11.mem_init1 = 2048'h00001000000000000000000000000000000082000000010000000000000000000000000000000000000000000000000000000000100000000000001000000001000000000000000000000000000000000000000000080000000000A04000000000000100201000000200008000000000000000000000000000000000000000080000000040000000000000000000002000040000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000080002000040000000080000000000000000040000000000000000040000000000000402110000000000000001000000000010000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_width = 12,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "clock0",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_11.port_a_first_address = 12288,
		ram_block1a_11.port_a_first_bit_number = 2,
		ram_block1a_11.port_a_last_address = 16383,
		ram_block1a_11.port_a_logical_ram_depth = 32768,
		ram_block1a_11.port_a_logical_ram_width = 3,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[4]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "rom_map.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 2048'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000100000000100004000000004000000002000000004000040000000040001000040000000000000800020000800000000000010000800000000C020000000000000002000000002000000000000040001000000001000020000000000000800000000400000000400010000400000000400000000200000000000004000000000000000402000800800018000008010080000000000001000000000000020000800000000000020000000000000400030000400010000000010000,
		ram_block1a_12.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_width = 12,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "clock0",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_12.port_a_first_address = 16384,
		ram_block1a_12.port_a_first_bit_number = 0,
		ram_block1a_12.port_a_last_address = 20479,
		ram_block1a_12.port_a_logical_ram_depth = 32768,
		ram_block1a_12.port_a_logical_ram_width = 3,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[4]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "rom_map.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008080001000040000000000000000040000000020000000010000000000000000000000000010000000008000000008000000008000000008000100008000800000000000000000080002000000001000000001000000001000020000800000000000000000000010000000010000000000000000000000200000000600000000200402020000C0000080000000018000A000000002000000001000000000000000000000020000000060000800000000400030000000000000000010000,
		ram_block1a_13.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_width = 12,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "clock0",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_13.port_a_first_address = 16384,
		ram_block1a_13.port_a_first_bit_number = 1,
		ram_block1a_13.port_a_last_address = 20479,
		ram_block1a_13.port_a_logical_ram_depth = 32768,
		ram_block1a_13.port_a_logical_ram_width = 3,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[4]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "rom_map.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000020000800000000000000000000010000000000000000008000000010000000000000000000000000004000000000000010004000100000000000000000000000000000000000000000000000000000000000000020000000000000800000000800000000200008000000000000000000000000000000100008050080002000001400000000000000080000000080000000040000000000000000000000000020000000000000000000000000008000,
		ram_block1a_14.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_width = 12,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "clock0",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_14.port_a_first_address = 16384,
		ram_block1a_14.port_a_first_bit_number = 2,
		ram_block1a_14.port_a_last_address = 20479,
		ram_block1a_14.port_a_logical_ram_depth = 32768,
		ram_block1a_14.port_a_logical_ram_width = 3,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[5]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "rom_map.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_width = 12,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "clock0",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_15.port_a_first_address = 20480,
		ram_block1a_15.port_a_first_bit_number = 0,
		ram_block1a_15.port_a_last_address = 24575,
		ram_block1a_15.port_a_logical_ram_depth = 32768,
		ram_block1a_15.port_a_logical_ram_width = 3,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[5]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "rom_map.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_16.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_width = 12,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "clock0",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_16.port_a_first_address = 20480,
		ram_block1a_16.port_a_first_bit_number = 1,
		ram_block1a_16.port_a_last_address = 24575,
		ram_block1a_16.port_a_logical_ram_depth = 32768,
		ram_block1a_16.port_a_logical_ram_width = 3,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[5]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "rom_map.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_17.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_width = 12,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "clock0",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_17.port_a_first_address = 20480,
		ram_block1a_17.port_a_first_bit_number = 2,
		ram_block1a_17.port_a_last_address = 24575,
		ram_block1a_17.port_a_logical_ram_depth = 32768,
		ram_block1a_17.port_a_logical_ram_width = 3,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[6]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "rom_map.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_18.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_width = 12,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "clock0",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_18.port_a_first_address = 24576,
		ram_block1a_18.port_a_first_bit_number = 0,
		ram_block1a_18.port_a_last_address = 28671,
		ram_block1a_18.port_a_logical_ram_depth = 32768,
		ram_block1a_18.port_a_logical_ram_width = 3,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[6]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "rom_map.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_19.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_width = 12,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "clock0",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_19.port_a_first_address = 24576,
		ram_block1a_19.port_a_first_bit_number = 1,
		ram_block1a_19.port_a_last_address = 28671,
		ram_block1a_19.port_a_logical_ram_depth = 32768,
		ram_block1a_19.port_a_logical_ram_width = 3,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[6]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "rom_map.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_20.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_width = 12,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "clock0",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_20.port_a_first_address = 24576,
		ram_block1a_20.port_a_first_bit_number = 2,
		ram_block1a_20.port_a_last_address = 28671,
		ram_block1a_20.port_a_logical_ram_depth = 32768,
		ram_block1a_20.port_a_logical_ram_width = 3,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[7]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "rom_map.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_21.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_width = 12,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "clock0",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_21.port_a_first_address = 28672,
		ram_block1a_21.port_a_first_bit_number = 0,
		ram_block1a_21.port_a_last_address = 32767,
		ram_block1a_21.port_a_logical_ram_depth = 32768,
		ram_block1a_21.port_a_logical_ram_width = 3,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[7]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "rom_map.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_22.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_width = 12,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "clock0",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_22.port_a_first_address = 28672,
		ram_block1a_22.port_a_first_bit_number = 1,
		ram_block1a_22.port_a_last_address = 32767,
		ram_block1a_22.port_a_logical_ram_depth = 32768,
		ram_block1a_22.port_a_logical_ram_width = 3,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cycloneii_ram_block";
	cycloneii_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.ena0(wire_deep_decode_eq[7]),
	.portaaddr({address_a_wire[11:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbrewe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "rom_map.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_23.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_width = 12,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "clock0",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_disable_ce_on_output_registers = "on",
		ram_block1a_23.port_a_first_address = 28672,
		ram_block1a_23.port_a_first_bit_number = 2,
		ram_block1a_23.port_a_last_address = 32767,
		ram_block1a_23.port_a_logical_ram_depth = 32768,
		ram_block1a_23.port_a_logical_ram_width = 3,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cycloneii_ram_block";
	assign
		address_a_sel = address_a[14:12],
		address_a_wire = address_a,
		q_a = wire_mux2_result;
endmodule //rom_map_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module rom_map (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[14:0]  address;
	input	  clock;
	output	[2:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [2:0] sub_wire0;
	wire [2:0] q = sub_wire0[2:0];

	rom_map_altsyncram	rom_map_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "rom_map.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "32768"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "15"
// Retrieval info: PRIVATE: WidthData NUMERIC "3"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "rom_map.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone II"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "32768"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "CLOCK0"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "15"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "3"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 15 0 INPUT NODEFVAL "address[14..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 3 0 OUTPUT NODEFVAL "q[2..0]"
// Retrieval info: CONNECT: @address_a 0 0 15 0 address 0 0 15 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 3 0 @q_a 0 0 3 0
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map.vhd TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map_inst.vhd FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL rom_map_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
